### ISSUE TITLE
'ModuleNotFoundError' 

### ISSUE THREAD

**Issue by mnrv-ae** [nicbou/burgeramt-appointments-websockets#10]
When I try to run '$ appointments' I get the following output:

```
Traceback (most recent call last):
  File "/usr/local/bin/appointments", line 2, in <module>
    from appointments.appointments import watch_for_appointments
ModuleNotFoundError: No module named 'appointments'
```

How should I proceed?

**Comment by nicbou** [comment]
I didn't package it properly, my bad. I'll fix it when I find a few minutes.

In the meantime, try running the package from source: pull this repository, and run `pip install -e /path/to/repo`. The appointments package should exist.

**Comment by nicbou** [comment]
It's fixed. Try again: `pip install --upgrade berlin-appointment-finder`
