### ISSUE TITLE
Installation issue due to use of legacy setup.py

### ISSUE THREAD

**Issue by subodhkarwa** [nicbou/burgeramt-appointments-websockets#12]
I am a non-python developer and I see the following issues while executing pip for first time:

  Building wheel for lxml (setup.py) ... error
  error: subprocess-exited-with-error

...
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [145 lines of output]
      Building lxml version 4.7.1.
      Building without Cython.
      Building against libxml2 2.9.4 and libxslt 1.1.29
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-12-x86_64-3.11
      creating build/lib.macosx-12-x86_64-3.11/lxml
      copying src/lxml/_elementpath.py -> build/lib.macosx-12-x86_64-3.11/lxml
      copying src/lxml/sax.py -> build/lib.macosx-12-x86_64-3.11/lxml
       ...
        clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -DCYTHON_CLINE_IN_TRACEBACK=0 -Isrc -Isrc/lxml/includes -I/usr/local/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c src/lxml/etree.c -o build/temp.macosx-12-x86_64-3.11/src/lxml/etree.o -w -flat_namespace
      src/lxml/etree.c:262403:23: error: no member named 'exc_type' in 'struct _err_stackitem'
          while ((exc_info->exc_type == NULL || exc_info->exc_type == Py_None) &&
                  ~~~~~~~~  ^
                  ..
                        cc -I/usr/include/libxml2 -c /var/folders/w4/whmqr_050bg0c71p9xy8kglh0000gp/T/xmlXPathInittburxmb2.c -o var/folders/w4/whmqr_050bg0c71p9xy8kglh0000gp/T/xmlXPathInittburxmb2.o
      cc var/folders/w4/whmqr_050bg0c71p9xy8kglh0000gp/T/xmlXPathInittburxmb2.o -lxml2 -o a.out
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
      
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lxml
  Running setup.py clean for lxml"
                  
...

**Comment by subodhkarwa** [comment]
Post the first error stack, it fails in subsequent step:

...
 Rolling back uninstall of lxml
  Moving to /usr/local/lib/python3.11/site-packages/lxml-4.9.2.dist-info/
   from /usr/local/lib/python3.11/site-packages/~xml-4.9.2.dist-info
  Moving to /usr/local/lib/python3.11/site-packages/lxml/
   from /usr/local/lib/python3.11/site-packages/~xml
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> lxml

...

**Comment by nicbou** [comment]
This is not an issue with the script. I do not provide technical support.

**Comment by nicbou** [comment]
Added info to README in f11f01c
