### ISSUE TITLE
 Error on running pip install berlin-appointment-finder

### ISSUE THREAD

**Issue by abdulbasit18** [nicbou/burgeramt-appointments-websockets#13]
Getting an error on running `pip install berlin-appointment-finder`
![Screenshot 2023-04-14 at 10 41 47](https://user-images.githubusercontent.com/15695892/231992402-63bd434c-006a-4130-b65e-836096d2527f.png)

**Comment by nicbou** [comment]
Google the error message. It's an issue with installing lxml on your platform and has nothing to do with this project.

**Comment by nicbou** [comment]
Added info to README in f11f01c
