### ISSUE TITLE
[NOT-AN-ISSUE] Is it possible to adapt this for the immigration office?

### ISSUE THREAD

**Issue by Mauker1** [nicbou/burgeramt-appointments-websockets#20]
First of all, many thanks for working to create this! Amazing job!

Now I was wondering whether or not it's possible to adjust this project to work with the immigration office site: https://otv.verwalt-berlin.de/ams/TerminBuchen - which is also a pain to get an appointment :)

**Comment by nicbou** [comment]
From the README:

> This tool can't book the appointment for you. It can't look for Ausländerbehörde appointments. These features will not be implemented.

**Comment by Mauker1** [comment]
Oh, that's on me, I didn't see it. Thanks for the info tho! And once again, good job :)
