### ISSUE TITLE
Not an issue, but I must say a thousand thanks

### ISSUE THREAD

**Issue by gerardmarquinarubio** [nicbou/burgeramt-appointments-websockets#7]
As a young software developer new in Berlin I had to accept a job offer but the next appointment for anmeldung was in 8 weeks, thanks to your tool I got one the same day. For you it must be insignificant and you will have received thousands of similar messages but for me it means the world. Thanks ❤️

**Comment by nicbou** [comment]
Thank you for the kind words, glad it helped!
