### ISSUE TITLE
Add service (and thank you!)

### ISSUE THREAD

**Issue by nivb06** [nicbou/burgeramt-appointments-websockets#9]
Is it possible to add service #121593?
I'm trying to book an appointment there for weeks 

Thanks!!

**Comment by nicbou** [comment]
Yes, you just need to edit the first few lines of the script.

It cannot be added to the tool on All About Berlin without permission from the city of Berlin. So far, my emails went unanswered. This could be because they are marked as spam (like earlier last year).
